---
title: "Data Prep Rural Group"
author: "Luvuyo Magwaza"
date: '2022-07-27'
output: html_document
---
```{r loading libs}
library(tidyverse)
library(haven)
```

```{r loading in dataset}
rural_group <- read_csv("~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work /(SA) - tGiver Motives Across Cultures - Rural Group_July 27, 2022_10.19.csv")
view(rural_group)
```

```{r data cleaning}
# Creating a data set that only contains variables I am interested in 

rural_group %>%
  select(Finished, Country_living, `Residential Area`:Gender, Race, family_size, Religion, 
         ends_with("_2"), Char_Generosity:William, 
         SubjectiveSES_1, Acountry_match, Wcountry_match, Areligion_match, Wreligion_match,
         Afamily_match, Wfamily_match, Ahobby_match, Whobby_match, Aaffliction_match, 
         Waffliction_match, `Anika_y%`, `William_y%`, Anika_xfold, William_xfold,
         -(SubjectiveSES_3_2), -(Enjoy_activities_2), -(PersonalExperience_2), -(PassionProblem_2)) -> rural_group_few 

# Renaming some variables 
rural_group_few  %>%
  rename(Residential_area = `Residential Area`, Residential_live = `Residential Live`, Level_of_education = ObjectiveSES_2,
         Hh_income_pa = ObjectiveSES_1, Family_size = family_size, N_generosity = N_Generosity2) -> rural_group_few

# Dropping observations that did not complete the survey 
rural_group_few %>% 
  filter(Finished == TRUE) -> rural_group_few

# Dropping observations that do not live in rural areas
rural_group_few %>% 
  filter(Residential_area == "Rural") -> rural_group_few

# Creating factors
glimpse(rural_group_few)
rural_group_few$Level_of_education <- as.factor(rural_group_few$Level_of_education)
rural_group_few$Hh_income_pa <- as.factor(rural_group_few$Hh_income_pa)
rural_group_few$Gender <- as.factor(rural_group_few$Gender)
rural_group_few$Race <- as.factor(rural_group_few$Race)
rural_group_few$Family_size <- as.factor(rural_group_few$Family_size)
rural_group_few$Religion <- as.factor(rural_group_few$Religion)
rural_group_few$SubjectiveSES_1 <- as.factor(rural_group_few$SubjectiveSES_1)
  
  
# Creating a tibble for the charitable and norm giving tasks 
rural_group_few %>% 
  select(Char_Community_2:Char_CauseArea_2) %>% #Starting with charitable choice  
  summarise(Community = mean(Char_Community_2),
            Country = mean(Char_Country_2),
            Ideology = mean(Char_Ideology_2),
            Religion = mean(Char_Religion_2),
            Generation = mean(Char_Generation_2),
            Species = mean(Char_Species_2),
            Cause_Affliction = mean(Char_CausePriority_2),
            Cause_Passion = mean(Char_CauseArea_2))
# Finding the standard deviation of each giving task
rural_group_few %>% 
  select(Char_Community_2:Char_CauseArea_2) %>% #Starting with charitable choice  
  summarise(Community = sd(Char_Community_2),
            Country = sd(Char_Country_2),
            Ideology = sd(Char_Ideology_2),
            Religion = sd(Char_Religion_2),
            Generation = sd(Char_Generation_2),
            Species = sd(Char_Species_2),
            Cause_Affliction = sd(Char_CausePriority_2),
            Cause_Passion = sd(Char_CauseArea_2))

tibble(Giving_Task = c("Community", "Country", "Ideology", "Religion", "Generation", "Species", "Cause_Affliction", "Cause_Passion"),
       Mean        = c(46, 43,	43,	52,	40,	39,	45,	41),
       Sd          = c(19.76197,	21.13539,	22.71762,	19.32356,	20.13256,	21.73747,	20.1365,	19.04083))  -> Char_choice

rural_group_few %>% 
  select(Norm_Community_2:Norm_AidTypePriority_2) %>% # Norm choice  
  summarise(Community = mean(Norm_Community_2),
            Country = mean(Norm_Country_2),
            Ideology = mean(Norm_Ideology_2),
            Religion = mean(Norm_Religion_2),
            Generation = mean(Norm_Generation_2),
            Species = mean(Norm_Species_2),
            Cause_Affliction = mean(Norm_CausPriority_2),
            Cause_Passion = mean(Norm_AidTypePriority_2))

rural_group_few %>% 
  select(Norm_Community_2:Norm_AidTypePriority_2) %>% # Norm choice  
  summarise(Community = sd(Norm_Community_2),
            Country = sd(Norm_Country_2),
            Ideology = sd(Norm_Ideology_2),
            Religion = sd(Norm_Religion_2),
            Generation = sd(Norm_Generation_2),
            Species = sd(Norm_Species_2),
            Cause_Affliction = sd(Norm_CausPriority_2),
            Cause_Passion = sd(Norm_AidTypePriority_2))

tibble(Giving_Task = c("Community", "Country", "Ideology", "Religion", "Generation", "Species", "Cause_Affliction", "Cause_Passion"),
       Mean        = c(43, 41,	39,	48,	39,	37,	43,	40),
       Sd          = c(21.8448,	23.5385,	23.05297,	22.75381,	20.55751,	22.41932,	21.08667,	20.48596))  -> Norm_choice # Rounding off two decimal places 

# Creating standard error and confidence interval values for Char_choice and Norm_choice tibbles 
Char_choice %>% 
  mutate(Se = Sd/sqrt(n())) %>% 
  mutate(CI = 1.96 * Se) -> Char_choice
  

Norm_choice %>% 
  mutate(Se = Sd/sqrt(n())) %>% 
  mutate(CI = 1.96 * Se) -> Norm_choice


```

### Saving new data frames 
```{r}
write.csv(rural_group_few,"~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work / rural_group_few.csv", row.names = FALSE)

write.csv(Char_choice,"~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work / Char_choice.csv", row.names = FALSE)

write.csv(Norm_choice,"~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work / Norm_choice.csv", row.names = FALSE)




```

