---
title: "Exploratory Data Analysis Rural group"
author: "Luvuyo Magwaza"
date: '2022-08-02'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
library(tidyverse)

Char_choice <- read_csv("~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work / Char_choice.csv")
Norm_choice <- read_csv("~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work / Norm_choice.csv")
rural_group_few <- read_csv("~/Google Drive/USF Semesters /Semesters/2022 Fall/Rural Group Summer Work / rural_group_few.csv")

```

### Average given in giving tasks
```{r making plots}
# Creating charitable choice graph 

Char_choice %>% 
  mutate(Giving_Task = fct_reorder(Giving_Task, Mean)) %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  ggplot(aes(x = Giving_Task, y = Mean)) + 
  geom_bar(stat = "identity", fill= "steelblue4", alpha=0.9)  + 
  ylim(0, 100) + 
  geom_errorbar(aes(x = Giving_Task, ymin = Mean - CI, ymax = Mean + CI), color = "black", size = 0.4, width = 0.4) +
  geom_text(aes(label = Mean), vjust = -0.3, color = "black", position = position_nudge(y = -2.0)) +
  coord_flip() + 
  labs(title = "Personal Donation Choice: Rural Group  ", 
       subtitle = "How much do you want to donate?",
       y = "Percentage Given to Charity B", 
       x = "") 

# Creating norms choice graph
Norm_choice %>% 
  mutate(Giving_Task = fct_reorder(Giving_Task, Mean)) %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  ggplot(aes(x = Giving_Task, y =Mean)) + 
  geom_bar(stat = "identity", fill= "steelblue4", alpha=0.9)  + 
  ylim(0, 100) + 
  geom_errorbar(aes(x = Giving_Task, ymin = Mean - CI, ymax = Mean + CI), color = "black", size = 0.4, width = 0.4) + 
  geom_text(aes(label = Mean), vjust = -0.3, color = "black", position = position_nudge(y = -2.0)) +
  coord_flip() + 
  labs(title = "Norms Donation Choice: Rural Group ", 
       subtitle = "How much do people think you ought to donate?",
       y = "Percentage Given to Charity B", 
       x = "") 
```

### General generosity in norms and personal choice 
```{r}
rural_group_few %>% 
  ggplot(aes(x = N_generosity,
             y = Char_Generosity )) +
  geom_point() + geom_smooth(method = lm, se = TRUE, span = 0.2) 
# we can see that there is a strong directly proportional relationship between norm generosity and personal choice generosity. 
```

### Giving by hh income 
```{r}
rural_group_few %>% 
  group_by(Hh_income_pa) %>% 
  summarise(Personal_gen = mean(Char_Generosity)) %>% 
  mutate(Hh_income_pa = fct_reorder(Hh_income_pa, Personal_gen)) %>% 
  ggplot() + geom_bar(aes(x = Hh_income_pa, y = Personal_gen), stat = "identity", fill= "steelblue4", alpha=0.9 ) +
  ylim(0, 1612) + 
  coord_flip()
# below is everything I did above but in percentage form
rural_group_few %>% 
  group_by(Hh_income_pa) %>% 
  summarise(Personal_gen = mean(Char_Generosity)/1612) %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  mutate(Hh_income_pa = fct_reorder(Hh_income_pa, Personal_gen)) %>% 
  ggplot(aes(x = Hh_income_pa, y = Personal_gen)) + geom_bar(stat = "identity", fill= "steelblue4", alpha=0.9 ) +
  ylim(0, 1) + 
  geom_text(aes(label = Personal_gen), vjust = 0.5, color = "black", position = position_nudge(y = -0.05)) +
  coord_flip() 

```

### Giving by gender 
```{r}
rural_group_few %>% 
  group_by(Gender) %>% 
  summarise(avg_donation = mean(Char_Generosity)) %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  mutate(Gender = fct_reorder(Gender, avg_donation)) %>% 
  ggplot(aes(x = Gender, y = avg_donation)) +
  geom_bar( stat = "identity", fill = "steelblue4", alpha = 0.9, width = 0.5) +
  ylim(0, 1612) +
  geom_text(aes(label = avg_donation), vjust = 1.5, color = "black")
```

### Age demographics
```{r}
rural_group_few %>% 
  group_by(Gender) %>% 
  summarise(avg_age = mean(Age)) %>% 
  ggplot() +
  geom_bar(aes(x = Gender, y = avg_age), stat = "identity", width = 0.5, fill = "steel blue")

rural_group_few %>% 
  group_by(Gender) %>% 
  summarise(count = n()) %>% 
  ggplot() +
  geom_bar(aes(x = Gender, y = count), stat = "identity", width = 0.5, fill = "steel blue")
  
```


